name: Check markdown file

on:
  workflow_call:
    inputs:
      fix:
        type: boolean
        default: false
      globs:
        type: string
        required: true

permissions: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
        with:
          fix: ${{ inputs.fix }}
          globs: ${{ inputs.globs }}
