name: Check markdown file

on:
  workflow_call:
    inputs:
      fix:
        type: boolean
        default: false
      globs:
        type: string
        required: true

permissions: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@eb5ca3ab411449c66620fe7f1b3c9e10547144b0 # v18.0.0
        with:
          fix: ${{ inputs.fix }}
          globs: ${{ inputs.globs }}
