name: Check markdown file

on:
  workflow_call:
    inputs:
      fix:
        type: boolean
        default: false
      globs:
        type: string
        required: true

permissions: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16.0.0
        with:
          fix: ${{ inputs.fix }}
          globs: ${{ inputs.globs }}
