name: Checks for pull request

on:
  pull_request:
    branches:
      - main

jobs:
  path-filter:
    outputs:
      markdown: ${{steps.changes.outputs.markdown}}
      actions: ${{steps.changes.outputs.actions}}
      ts: ${{steps.changes.outputs.ts}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            markdown:
              - ./**/*.md
              - CHANGELOG.md
            actions:
              - .github/workflows/*.yml
              - .github/workflows/*.yaml
              - aqua.yaml
              - CHANGELOG.md
            ts:
              - .github/workflows/push.yml
              - .github/workflows/_check-deno.yml
              - ./**/*.ts
              - deno.jsonc
              - CHANGELOG.md
  check-markdown:
    needs: path-filter
    if: needs.path-filter.outputs.markdown == 'true'
    uses: ./.github/workflows/_check-markdown.yml
    permissions: {}
    with:
      globs: "./**/*.md"
  check-actions:
    needs: path-filter
    if: needs.path-filter.outputs.actions == 'true'
    uses: ./.github/workflows/_check-actions.yml
    permissions:
      contents: read
  check-deno:
    needs: path-filter
    if: needs.path-filter.outputs.ts == 'true'
    uses: ./.github/workflows/_check-deno.yml
    permissions:
      contents: read
  status-check:
    runs-on: ubuntu-latest
    needs:
      - check-actions
      - check-deno
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
